# Generated by Django 5.2.11 on 2026-02-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isAvailable',
            field=models.BooleanField(default=True, help_text='Is this product available for purchase'),
        ),
    ]
