# Generated by Django 5.2.11 on 2026-02-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_isavailable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isAvailable',
            new_name='available',
        ),
    ]
